### ISSUE TITLE
🐞 Admin Portal - Tally Ceremony - Cancel tally ceremony does not seem to work

### ISSUE THREAD

**Issue by edulix** [sequentech/meta#1098]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I have attached screenshots and/or the specific steps to reproduce this issue.
- [X] I have attached a minimal `election.json` configuration to reproduce this issue (provide one for each different use-case).

### Current Behavior

When clicking in a tally's cancel action, it seems to fail:

<img width="1382" alt="image" src="https://github.com/sequentech/meta/assets/81968/f9bc25a7-5efa-4f67-adc3-e393c1f10e20">

### Expected Behavior

It should work.

### Steps To Reproduce

-

### Environment

-

### Tasks

```[tasklist]
# Tasks
- [x] Issue has been triaged
- [x] Successful replication of the defect
- [x] Successful defect resolution merged
```

```[tasklist]
# Main PRs
- [ ] https://github.com/sequentech/step/pull/514
```

**Comment by xalsina-sequent** [comment]
The issue is in [windmill -> tally ceremony](https://github.com/sequentech/step/blob/main/packages/windmill/src/services/ceremonies/tally_ceremony.rs#L383) where any update to the tally cerimory does a check to see if there is a sufficient number of connected trustees.

One possible solution could be to ignore this check if the new execution status to set is cancelled.
